version: 2
updates:
  - package-ecosystem: npm
    directory: "/elparadisogonzalo"
    schedule:
      interval: 1minute

  - package-ecosystem: bundler
    directory: "/elparadisogonzalo"
    schedule:
      interval: 1minute

  - package-ecosystem: composer
    directory: "/elparadisogonzalo"
    schedule:
      interval: 1minute

  - package-ecosystem: devcontainers
    directory: "/elparadisogonzalo"
    schedule:
      interval: 1minute

  - package-ecosystem: dotnet-sdk
    directory: "/elparadisogonzalo"
    schedule: 1minute

  - package-ecosystem: maven
    directory: "/elparadisogonzalo"
    schedule:
      interval: 1minute

  - package-ecosystem: mix
    directory: "/elparadisogonzalo"
    schedule:
      interval: 1minute

  - package-ecosystem: cargo
    directory: "/elparadisogonzalo"
    schedule:
      interval: 1minute

  - package-ecosystem: gradle
    directory: "/elparadisogonzalo"
    schedule:
      interval: 1minute

  - package-ecosystem: nuget
    directory: "/elparadisogonzalo"
    schedule:
      interval: 1minute

  - package-ecosystem: gomod
    directory: "/elparadisogonzalo"
    schedule:
      interval: 1minute

  - package-ecosystem: docker
    directory: "/elparadisogonzalo"
    schedule:
      interval: 1minute

  - package-ecosystem: docker-compose
    directory: "/elparadisogonzalo"
    schedule:
      interval: 1minute

  - package-ecosystem: elm
    directory: "/"
    schedule:
      interval: 1minute

  - package-ecosystem: gitsubmodule
    directory: "/elparadisogonzalo"
    schedule:
      interval: 1minute

  - package-ecosystem: github-actions
    directory: "/elparadisogonzalo"
    schedule:
      interval: 1minute

  - package-ecosystem: pip
    directory: "/elparadisogonzalo"
    schedule:
      interval: 1minute

  - package-ecosystem: terraform
    directory: "/elparadisogonzalo"
    schedule:
      interval: 1minute

  - package-ecosystem: pub
    directory: "/elparadisogonzalo"
    schedule:
      interval: 1minute

  - package-ecosystem: swift
    directory: "/elparadisogonzalo"
    schedule:
      interval: daily

  - package-ecosystem: bun
    directory: "/elparadisogonzalo"
    schedule:
      interval: 1minute

  - package-ecosystem: uv
    directory: "/elparadisogonzalo"
    schedule:
      interval: 1minute
