- name: Set up gcloud Cloud SDK environment
  uses: google-github-actions/setup-gcloud@v2.1.4
  <!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=AW-16569640454"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'AW-16569640454');
</script> runs-on:Github/Gitlab Shared Runner       - name: Setup Go environment
                                                 Setup Cloud Run
                                                 App Engine
                                                 Compute Engine
                                                 Kubernetes Engine
                                                 Storage
                                                 SQL
                                                 billing Account
                                                 mailto
                                                 Extension   
                                                 Sync
                                                 ether.js
                                                 debug
                                                 remote 
                                                 web3.js
      contents: 'write'
      
       id-token: 'write'

Google Cloud Configuration for Development Container
version: '1.0'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/universal:2
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/workspace/google_credentials.json
      - PROJECT_ID=elparadisogonzalo-project-id  # Use your actual Google Cloud Project ID here
      - ZONE=# Google Cloud Configuration for Development Container
version: '1.0'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/universal:2
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/workspace/google_credentials.json
      - PROJECT_ID=elparadisogonzalo-project-id  # Use your actual Google Cloud Project ID here
      - ZONE=global
      - REGION=universal
    ports:
      - "22:22"  # SSH access
      - "8080:8080"  # Example service port
    volumes:
      - ./google_credentials.json:/workspace/google_credentials.json:ro  # Mounting Google credentials
      - ./src:/workspace/src  # Your code or project directory
    features:
      - ghcr.io/devcontainers/features/sshd:1  # Install SSH server
    ssh:
      enabled: true
      public_key: "ssh-rsa AAAAB3NzaC1yc2EA...xQOMq1Mds4D3ey6bWQ1uBEHdP3LiUzS2FMRCy3GeQoM"  # SSH public key for access
    commands:
      - "gcloud auth activate-service-account --key-file=/workspace/google_credentials.json"  # Authenticate with Google Cloud
      - "gcloud config set project ${PROJECT_ID}"  # Set Google Cloud project ID
      - "gcloud config set compute/zone ${ZONE}"  # Set Google Cloud compute zone
